numademo: fix incompatible pointer types
a7c4bc7 introduced a error about incompatible pointer types.

test/move_pages.c:35:39: error: passing argument 2 of
'numa_node_size' from incompatible pointer type
[-Werror=incompatible-pointer-types]
    if (numa_node_size(a, &free_node_sizes) > 0)
			     ^^
Unified variable type and fix it.

Signed-off-by: Hongzhi.Song <hongzhi.song@windriver.com>