missing sys/stat.h include in shm.c for fstat64()
building on my x86_64 system shows:
shm.c: In function attach_shared:
shm.c:139:2: warning: implicit declaration of function fstat64

and that's simply due to sys/stat.h not being included

the homepage doesnt list a git tree or anything, so hand pasting: